### ISSUE TITLE
How can I export metrics to prometheus or grafana?

### ISSUE THREAD

**Issue by sawaca96** [epoch8/airflow-exporter#100]
I'm use [airflow-stable helm chart](https://github.com/airflow-helm/charts/tree/main/charts/airflow) and airflow-exporter 

so I can see metrics from /admin/metrics 

but I want to export metrics to grafana. How can I export this metrics ?? 

# Note
airflow version `apache/airflow:2.0.2-python3.8`
helm chart version `8.2`

**Comment by elephantum** [comment]
@sawaca96 you need prometheus to collect metrics and point grafana to your prometheus instance

**Comment by elephantum** [comment]
https://prometheus.io/docs/prometheus/latest/configuration/configuration/
