### ISSUE TITLE
Setup continuos integration

### ISSUE THREAD

**Issue by elephantum** [epoch8/airflow-exporter#13]
Choose between CircleCI and TravisCI.

Create pipeline that

* performs `docker-compose up` for each `tests/airflow1.8-py2` and `test/airflow1.9-py3`
* waits for Airflow to start
* checks that `localhost:8080/admin/metrics` returns 200 OK with correctly formatted metrics

**Comment by hydrosquall** [comment]
@elephantum I can look into this on the weekend :)

**Comment by elephantum** [comment]
@hydrosquall that would be great, we started using Travis-CI for internal project, would be nice to stick with it.

**Comment by elephantum** [comment]
Fixed by #20 and #27
