### ISSUE TITLE
Airflow 1.10 with rbac enabled doesn't show up this plugin in UI's menu

### ISSUE THREAD

**Issue by c4milo** [epoch8/airflow-exporter#22]
A patch for Airflow's plugin manager was done in https://github.com/apache/incubator-airflow/pull/4036. I believe the plugin needs add another class extending from `AppBuilderBaseView`.

**Comment by elephantum** [comment]
@c4milo thanks for reporting, we'll take a look into it

**Comment by phani8996** [comment]
@c4milo #28  addresses this issue. Unfortunately for this to work, we have to wait till airflow releases plugin support when rbac enabled. This future currently available with dev version of airflow.

**Comment by elephantum** [comment]
Fixed in v0.5

**Comment by rushtokunal** [comment]
@elephantum I tried the plugin with version 2.0 (master) branch of Airflow and it doest work. Do we still have to use the /admin/metrics after the link of the UI? I have RBAC enabled
