### ISSUE TITLE
Heavy CPU usage on large number of DAGs

### ISSUE THREAD

**Issue by elephantum** [epoch8/airflow-exporter#35]
As discussed here: https://github.com/epoch8/airflow-exporter/issues/23#issuecomment-441232655 there's an issue with collecting metrics on the database with large number of DAGs.

We need:

- a test case to reproduce this issue
- investigate what's causing CPU usage
- make a fix

**Comment by d-goldin** [comment]
In our fork, we have applied a fix like: https://github.com/soundcloud/airflow-exporter/commit/41a72ed19bf7a2de36fff76441ca1d0d5ddd08b9 - maybe it's something that could work for you too or potentially be upstreamed. This mitigates the issue of workers running this query, which caused the biggest chunk of load for us. Implementing a description function would still probably be better, but was not overly urgent to us. (CC @ebartels)

**Comment by d-goldin** [comment]
Seems like it's actually already fixed using describe in 0.5.1, so we will try that one instead.

**Comment by elephantum** [comment]
I believe this is obsolete. Closing
