### ISSUE TITLE
Installation Clarification

### ISSUE THREAD

**Issue by hydrosquall** [epoch8/airflow-exporter#4]
To get this to work, I had to move the `prometheus_exporter` directly into the `/plugins` directory, because my python path was having trouble finding the `prometheus_exporter.db` module. In other words, my directory looked like

```
$AIRFLOW_HOME/plugins/prometheus_exporter/prometheus_exporter.py
$AIRFLOW_HOME/plugins/prometheus_exporter/db/store.py
...
```

rather than what would happen if I followed the exact install instructions

```
$AIRFLOW_HOME/plugins/prometheus_exporter/prometheus_exporter/prometheus_exporter.py
$AIRFLOW_HOME/plugins/prometheus_exporter/prometheus_exporter/db/store.py
...
```

I wanted to check whether this was the experience of other people too, or if this is just an quirk of my particular airflow setup.

If it's the first case, I can make a PR later to clarify the installation directions. Alternately, I would recommend putting the plugin directly in the git project root directory rather than having a subfolder, similar to what is done with many of the other published airflow plugins (https://github.com/airflow-plugins/salesforce_plugin, etc)

**Comment by elephantum** [comment]
Agreed, this is an issue on our side. We'll move plugin code to the root of the repository.

**Comment by elephantum** [comment]
@cleverCat перетащи плз код плагина в корень, а `screenshots/` давай выпилим совсем и заменим ссылками на картинки отсюда: https://epoch8.github.io/2018/08/03/monitoring-airflow-with-prometheus.html
