### ISSUE TITLE
Airflow 2.0.0 Beta with rbac enabled doesn't show up this plugin in UI's menu

### ISSUE THREAD

**Issue by rushtokunal** [epoch8/airflow-exporter#40]
I downloaded the latest version of the code and followed the steps. It work when RBAC is not enabled but I enable RBAC the plugin doesnt show up in the UI

**Comment by rushtokunal** [comment]
Can you help with this issue?

**Comment by elephantum** [comment]
@rushtokunal sorry, currently we’re using 1.9 airflow, so we didn’t see this issue. 

We’re considering to try 2.0 in Q1

**Comment by rushtokunal** [comment]
@elephantum are you planning on implementing this feature in 2.0 this quarter? I was looking at statsd but felt it’s just another layer and doesn’t give me any added benefit

**Comment by rushtokunal** [comment]
@elephantum - i see that the plugin is compatible with Airflow 10.3, does it mean it is now complatible with RBAC as well?

**Comment by elephantum** [comment]
@rushtokunal I don't know yet.

RBAC is implemented as a separate set of views if I'm not mistaken. It should be tested.

We're still using 10.2 and no RBAC

**Comment by elephantum** [comment]
@rushtokunal can you check if the latest version of the plugin works correctly?

We added rbac support for 1.10 some time ago.

**Comment by elephantum** [comment]
Fixed by https://github.com/epoch8/airflow-exporter/pull/90
