### ISSUE TITLE
Deliver plugin as a python package

### ISSUE THREAD

**Issue by huntcsg** [epoch8/airflow-exporter#44]
Airflow has the ability to load plugins as python packages.

I'd be happy to contribute a setup.py and do release management to pypi if you are interested.

Alternatively, if you are not interested in doing that out of this repo I can set up a fork with the necessary setup.py release management tooling.

See https://airflow.apache.org/plugins.html#plugins-as-python-packages for some info.

**Comment by elephantum** [comment]
@huntcsg feel free to make a PR. We’ll be glad to accept it

**Comment by elephantum** [comment]
Solved by #48
