### ISSUE TITLE
Breaking change in Airflow 1.10.3(rc2) - removal of DagStat class

### ISSUE THREAD

**Issue by fahran** [epoch8/airflow-exporter#46]
Unfortunately a class that the exporter depends on, DagStat, has been removed in the latest version of Airflow (tested with v1.10.3rc2)

The error as reported in the UI is: "Broken plugin: [/usr/local/airflow/plugins/airflow-exporter-0.5.4/prometheus_exporter.py] cannot import name 'DagStat'"

From the changelog: https://github.com/apache/airflow/blob/master/CHANGELOG.txt, the relevant line is: [AIRFLOW-3573] Remove DagStat table (#4378). That jira ticket is available here: https://issues.apache.org/jira/browse/AIRFLOW-3573, and contains the commit log etc.

Looking at the code, three fields are used from DagStat (id, state & count). Looking at airflow's www/views.py code (and the modification made to it in light of [AIRFLOW-3573], tagged as [AIRFLOW-3561], commit# 0cc078a86d00c0f798b2b26d828126be99af9c6c) it seems like DagRun would work instead. https://github.com/apache/airflow/blob/6970b233964ee254bbb343ed8bdc906c2f7bd974/airflow/www/views.py#L278

Do you guys have any thoughts?

**Comment by sockeye44** [comment]
Just encountered the same problem, looks like switching to DagRun really solves it. Created PR #47 with a fix

**Comment by elephantum** [comment]
@fahran for now it's impossible to preserve compatibility with 1.10.3 and previous versions simultaneously. (possible but harder)

I merged @sockeye44 PR into branch `airflow-1.10.3` use it to have plugin working.

**Comment by elephantum** [comment]
Closing this issue for now. Feel free to reopen if necessary.
