### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by continuum-akshay-jadhav** [epoch8/airflow-exporter#63]
Hi All,

Can someone let me know how to use this repo.

I cloned the code on my target machine on which airflow container is present and did pip install,

but could not get metrics as their was no endpoint created when i ran netstat -tulpn command.

Thanks.

**Comment by elephantum** [comment]
You need to do `pip install` inside the airflow container.

**Comment by continuum-akshay-jadhav** [comment]
Also do i need to only move airflow_exporter folder into the container or all the code from Repo.


Also let me know where in the container should i place the code.

Thank you so much

**Comment by elephantum** [comment]
You do not need repo at all. Latest version of exporter is published to pypi.

Just do `pip install`

**Comment by continuum-akshay-jadhav** [comment]
Thank you @elephantum ,

I have included a docker command pip install airflow-exporter in my docker file..
Hope it works

**Comment by elephantum** [comment]
@continuum-akshay-jadhav I will close this issue for now. Reopen if you have problems.

**Comment by continuum-akshay-jadhav** [comment]
Hi @elephantum ,

I tried pip install in my container but now my container is getting restarted always
